//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class bracket
    {
        public bracket()
        {
            this.bracketlinks = new HashSet<bracketlink>();
            this.bracketlinks1 = new HashSet<bracketlink>();
            this.competitoreventclassbrackets = new HashSet<competitoreventclassbracket>();
        }
    
        public int BracketID { get; set; }
        public int EventClassID { get; set; }
        public int BracketNumber { get; set; }
        public int BracketLevel { get; set; }
        public bool IsUpdated { get; set; }
        public bool IsSent { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual eventclass eventclass { get; set; }
        public virtual ICollection<bracketlink> bracketlinks { get; set; }
        public virtual ICollection<bracketlink> bracketlinks1 { get; set; }
        public virtual ICollection<competitoreventclassbracket> competitoreventclassbrackets { get; set; }
    }
}
