//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class bracketlink
    {
        public int BracketLinkID { get; set; }
        public int PriorBracketID { get; set; }
        public int NextBracketID { get; set; }
        public int LoserAdvanceCount { get; set; }
        public int WinnerAdvanceCount { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual bracket bracket { get; set; }
        public virtual bracket bracket1 { get; set; }
    }
}
