//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendareventtype
    {
        public calendareventtype()
        {
            this.calendarevents = new HashSet<calendarevent>();
        }
    
        public int CalendarEventTypeID { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool DetailCalendarEntry { get; set; }
        public bool OrganizationLevel { get; set; }
        public bool RaceEventLevel { get; set; }
        public bool EventClassLevel { get; set; }
        public string Parameters { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<calendarevent> calendarevents { get; set; }
    }
}
