//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendarevent
    {
        public int CalendarEventID { get; set; }
        public int CalendarEventTypeID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> RaceEventID { get; set; }
        public Nullable<int> EventClassID { get; set; }
        public bool AllDayEvent { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Description { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual calendareventtype calendareventtype { get; set; }
        public virtual eventclass eventclass { get; set; }
        public virtual organization organization { get; set; }
        public virtual raceevent raceevent { get; set; }
    }
}
