//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitoreventclassbracket
    {
        public int CompetitorEventClassBracketID { get; set; }
        public int PersonEventClassID { get; set; }
        public int BracketID { get; set; }
        public int Place { get; set; }
        public int Points { get; set; }
        public bool IsQualificationPlace { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual bracket bracket { get; set; }
        public virtual personeventclass personeventclass { get; set; }
    }
}
