//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            this.accounts = new HashSet<account>();
            this.raceevents = new HashSet<raceevent>();
            this.organizationroletypes = new HashSet<organizationroletype>();
        }
    
        public int CurrencyID { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<raceevent> raceevents { get; set; }
        public virtual ICollection<organizationroletype> organizationroletypes { get; set; }
    }
}
