//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbfield
    {
        public dbfield()
        {
            this.controldbfields = new HashSet<controldbfield>();
        }
    
        public int DbFieldID { get; set; }
        public int DbTableID { get; set; }
        public int DbFieldTypeID { get; set; }
        public string Name { get; set; }
        public int MaxLength { get; set; }
        public string Description { get; set; }
        public bool IsInSystem { get; set; }
        public bool IsDefined { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<controldbfield> controldbfields { get; set; }
        public virtual dbfieldtype dbfieldtype { get; set; }
        public virtual dbtable dbtable { get; set; }
    }
}
