//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventclass
    {
        public eventclass()
        {
            this.brackets = new HashSet<bracket>();
            this.calendarevents = new HashSet<calendarevent>();
            this.personeventclasses = new HashSet<personeventclass>();
            this.eventclasslinks = new HashSet<eventclasslink>();
            this.eventclasslinks1 = new HashSet<eventclasslink>();
            this.prizeawards = new HashSet<prizeaward>();
            this.qualificationclasses = new HashSet<qualificationclass>();
        }
    
        public int EventClassID { get; set; }
        public int RaceEventID { get; set; }
        public int RaceClassID { get; set; }
        public int BuildQualificationMethodID { get; set; }
        public int BuildBracketMethodID { get; set; }
        public int LinkType { get; set; }
        public int RacersPerHeat { get; set; }
        public int RacersPerClass { get; set; }
        public int RepechagePlaces { get; set; }
        public int RepechageQualifiers { get; set; }
        public decimal PrimaryClassCost { get; set; }
        public decimal SecondaryClassCost { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<bracket> brackets { get; set; }
        public virtual buildbracketmethod buildbracketmethod { get; set; }
        public virtual buildqualificationmethod buildqualificationmethod { get; set; }
        public virtual ICollection<calendarevent> calendarevents { get; set; }
        public virtual raceclass raceclass { get; set; }
        public virtual raceevent raceevent { get; set; }
        public virtual ICollection<personeventclass> personeventclasses { get; set; }
        public virtual ICollection<eventclasslink> eventclasslinks { get; set; }
        public virtual ICollection<eventclasslink> eventclasslinks1 { get; set; }
        public virtual ICollection<prizeaward> prizeawards { get; set; }
        public virtual ICollection<qualificationclass> qualificationclasses { get; set; }
    }
}
