//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventclasslink
    {
        public int EventClassLinkID { get; set; }
        public int PrimaryEventClassID { get; set; }
        public int SecondaryEventClassID { get; set; }
        public int LinkType { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual eventclass eventclass { get; set; }
        public virtual eventclass eventclass1 { get; set; }
    }
}
