//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizationroletype
    {
        public organizationroletype()
        {
            this.personorganizationroles = new HashSet<personorganizationrole>();
        }
    
        public int OrganizationRoleTypeID { get; set; }
        public int OrganizationID { get; set; }
        public int UsageType { get; set; }
        public int CompetitorLevel { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Parameters { get; set; }
        public int CurrencyID { get; set; }
        public decimal DuesAmount { get; set; }
        public int RenewalType { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual organization organization { get; set; }
        public virtual ICollection<personorganizationrole> personorganizationroles { get; set; }
    }
}
