//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.contacts = new HashSet<contact>();
            this.identitykeys = new HashSet<identitykey>();
            this.messagesubscriptions = new HashSet<messagesubscription>();
            this.personcomments = new HashSet<personcomment>();
            this.personmessages = new HashSet<personmessage>();
            this.personorganizationroles = new HashSet<personorganizationrole>();
            this.personproducts = new HashSet<personproduct>();
            this.preferences = new HashSet<preference>();
        }
    
        public int PersonID { get; set; }
        public bool IsDeleted { get; set; }
        public bool SuperUser { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public int NationalityID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Gender { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
        public virtual country country { get; set; }
        public virtual ICollection<identitykey> identitykeys { get; set; }
        public virtual ICollection<messagesubscription> messagesubscriptions { get; set; }
        public virtual ICollection<personcomment> personcomments { get; set; }
        public virtual ICollection<personmessage> personmessages { get; set; }
        public virtual ICollection<personorganizationrole> personorganizationroles { get; set; }
        public virtual ICollection<personproduct> personproducts { get; set; }
        public virtual ICollection<preference> preferences { get; set; }
    }
}
