//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class personevent
    {
        public personevent()
        {
            this.personeventclasses = new HashSet<personeventclass>();
            this.qualificationbrackets = new HashSet<qualificationbracket>();
            this.qualificationruns = new HashSet<qualificationrun>();
        }
    
        public int PersonEventID { get; set; }
        public int RaceEventID { get; set; }
        public int PersonOrganizationRoleID { get; set; }
        public int CompetitorNumber { get; set; }
        public int TransponderNumber { get; set; }
        public bool CheckedIn { get; set; }
        public decimal AmountOwing { get; set; }
        public decimal AmountPaid { get; set; }
        public string Description { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<personeventclass> personeventclasses { get; set; }
        public virtual raceevent raceevent { get; set; }
        public virtual personorganizationrole personorganizationrole { get; set; }
        public virtual ICollection<qualificationbracket> qualificationbrackets { get; set; }
        public virtual ICollection<qualificationrun> qualificationruns { get; set; }
    }
}
