//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeventclass
    {
        public personeventclass()
        {
            this.competitoreventclassbrackets = new HashSet<competitoreventclassbracket>();
        }
    
        public int PersonEventClassID { get; set; }
        public int PersonEventID { get; set; }
        public int EventClassID { get; set; }
        public bool CannotRace { get; set; }
        public Nullable<int> QualificationPlace { get; set; }
        public Nullable<double> QualificationTime { get; set; }
        public Nullable<int> QualificationPoints { get; set; }
        public int Place { get; set; }
        public int Points { get; set; }
        public decimal PrizeAmount { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<competitoreventclassbracket> competitoreventclassbrackets { get; set; }
        public virtual eventclass eventclass { get; set; }
        public virtual personevent personevent { get; set; }
    }
}
