//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class personranking
    {
        public personranking()
        {
            this.racerankings = new HashSet<raceranking>();
        }
    
        public int PersonRankingID { get; set; }
        public int ClassRegionRankingID { get; set; }
        public int PersonOrganizationRoleID { get; set; }
        public int Place { get; set; }
        public int RankPoints { get; set; }
        public int TotalPoints { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual classregionranking classregionranking { get; set; }
        public virtual personorganizationrole personorganizationrole { get; set; }
        public virtual ICollection<raceranking> racerankings { get; set; }
    }
}
