//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class personmessage
    {
        public int PersonMessageID { get; set; }
        public int MessageItemID { get; set; }
        public int PersonID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateSaved { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual messageitem messageitem { get; set; }
        public virtual person person { get; set; }
    }
}
