//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class placepointmatrix
    {
        public placepointmatrix()
        {
            this.eventlevels = new HashSet<eventlevel>();
            this.placepoints = new HashSet<placepoint>();
        }
    
        public int PlacePointMatrixID { get; set; }
        public int OrganizationID { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<eventlevel> eventlevels { get; set; }
        public virtual organization organization { get; set; }
        public virtual ICollection<placepoint> placepoints { get; set; }
    }
}
