//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualificationrun
    {
        public int QualificationRunID { get; set; }
        public int QualificationGroupID { get; set; }
        public int PersonEventID { get; set; }
        public int RunNumber { get; set; }
        public double Time { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual personevent personevent { get; set; }
        public virtual qualificationgroup qualificationgroup { get; set; }
    }
}
