//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class racelevelranking
    {
        public int RaceLevelRankingID { get; set; }
        public int EventLevelID { get; set; }
        public int ClassRegionRankingID { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual classregionranking classregionranking { get; set; }
        public virtual eventlevel eventlevel { get; set; }
    }
}
