//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class raceEntities : DbContext
    {
        public raceEntities()
            : base("name=raceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accounttype> accounttypes { get; set; }
        public virtual DbSet<bracket> brackets { get; set; }
        public virtual DbSet<bracketlink> bracketlinks { get; set; }
        public virtual DbSet<brackettemplate> brackettemplates { get; set; }
        public virtual DbSet<buildbracketmethod> buildbracketmethods { get; set; }
        public virtual DbSet<buildqualificationmethod> buildqualificationmethods { get; set; }
        public virtual DbSet<buildrankingmethod> buildrankingmethods { get; set; }
        public virtual DbSet<calendarevent> calendarevents { get; set; }
        public virtual DbSet<calendareventtype> calendareventtypes { get; set; }
        public virtual DbSet<classregionranking> classregionrankings { get; set; }
        public virtual DbSet<commenttype> commenttypes { get; set; }
        public virtual DbSet<competitoreventclassbracket> competitoreventclassbrackets { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<continent> continents { get; set; }
        public virtual DbSet<control> controls { get; set; }
        public virtual DbSet<controldbfield> controldbfields { get; set; }
        public virtual DbSet<controltype> controltypes { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<dbfield> dbfields { get; set; }
        public virtual DbSet<dbfieldtype> dbfieldtypes { get; set; }
        public virtual DbSet<dbtable> dbtables { get; set; }
        public virtual DbSet<eventclass> eventclasses { get; set; }
        public virtual DbSet<eventclasslink> eventclasslinks { get; set; }
        public virtual DbSet<eventlevel> eventlevels { get; set; }
        public virtual DbSet<eventorganization> eventorganizations { get; set; }
        public virtual DbSet<form> forms { get; set; }
        public virtual DbSet<identitykey> identitykeys { get; set; }
        public virtual DbSet<messageitem> messageitems { get; set; }
        public virtual DbSet<messagesubscription> messagesubscriptions { get; set; }
        public virtual DbSet<messagetype> messagetypes { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<organizationroletype> organizationroletypes { get; set; }
        public virtual DbSet<organizationtype> organizationtypes { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<personcomment> personcomments { get; set; }
        public virtual DbSet<personevent> personevents { get; set; }
        public virtual DbSet<personeventclass> personeventclasses { get; set; }
        public virtual DbSet<personmessage> personmessages { get; set; }
        public virtual DbSet<personorganizationrole> personorganizationroles { get; set; }
        public virtual DbSet<personproduct> personproducts { get; set; }
        public virtual DbSet<personranking> personrankings { get; set; }
        public virtual DbSet<placepoint> placepoints { get; set; }
        public virtual DbSet<placepointmatrix> placepointmatrices { get; set; }
        public virtual DbSet<preference> preferences { get; set; }
        public virtual DbSet<prizeaward> prizeawards { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<qualificationbracket> qualificationbrackets { get; set; }
        public virtual DbSet<qualificationclass> qualificationclasses { get; set; }
        public virtual DbSet<qualificationgroup> qualificationgroups { get; set; }
        public virtual DbSet<qualificationrun> qualificationruns { get; set; }
        public virtual DbSet<raceclass> raceclasses { get; set; }
        public virtual DbSet<raceevent> raceevents { get; set; }
        public virtual DbSet<raceeventregion> raceeventregions { get; set; }
        public virtual DbSet<racelevelranking> racelevelrankings { get; set; }
        public virtual DbSet<raceranking> racerankings { get; set; }
        public virtual DbSet<racetitleranking> racetitlerankings { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
