//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class raceranking
    {
        public int RaceRankingID { get; set; }
        public int PersonRankingID { get; set; }
        public int RaceIndex { get; set; }
        public int Place { get; set; }
        public int Points { get; set; }
        public bool UsedForRanking { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual personranking personranking { get; set; }
    }
}
