//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDFWebApp.Models.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.classregionrankings = new HashSet<classregionranking>();
            this.raceeventregions = new HashSet<raceeventregion>();
        }
    
        public int RegionID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> ContinentID { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Unum { get; set; }
        public int UnumSync { get; set; }
        public System.DateTime UnumTime { get; set; }
    
        public virtual ICollection<classregionranking> classregionrankings { get; set; }
        public virtual continent continent { get; set; }
        public virtual organization organization { get; set; }
        public virtual ICollection<raceeventregion> raceeventregions { get; set; }
    }
}
